import { createStorageSignedUrl } from "@/server/services/storage";
import { isMockMode } from "@/lib/app-config";
import { createClient } from "@/lib/supabase/server";
import { getMockTrackPreviewData } from "@/modules/dev/mock-data";
import type { Database } from "@/lib/database.types";
import type {
  TrackPreviewChannel,
  TrackPreviewData,
  TrackPreviewRender,
  TrackPreviewStatus,
  TrackPreviewUpload,
} from "@/modules/tracks/track-preview.types";

type TrackRow = Pick<
  Database["public"]["Tables"]["tracks"]["Row"],
  | "audio_storage_path"
  | "created_at"
  | "description"
  | "duration_seconds"
  | "failure_reason"
  | "generation_request_id"
  | "id"
  | "image_asset_id"
  | "mood"
  | "source_audio_url"
  | "status"
  | "style"
  | "tags"
  | "title"
  | "workspace_id"
>;

type GenerationRow = Pick<
  Database["public"]["Tables"]["generation_requests"]["Row"],
  | "final_prompt"
  | "id"
  | "mood"
  | "publish_mode"
  | "scheduled_at"
  | "style"
  | "target_youtube_channel_id"
>;

type ImageRow = Pick<
  Database["public"]["Tables"]["image_assets"]["Row"],
  "file_name" | "height" | "public_url" | "source" | "storage_path" | "width"
>;

type ChannelRow = Pick<
  Database["public"]["Tables"]["youtube_channels"]["Row"],
  "handle" | "id" | "thumbnail_url" | "title"
>;

type RenderRow = Pick<
  Database["public"]["Tables"]["video_renders"]["Row"],
  "failure_reason" | "id" | "status" | "track_id" | "video_storage_path"
>;

type UploadRow = Pick<
  Database["public"]["Tables"]["youtube_uploads"]["Row"],
  "failure_reason" | "id" | "scheduled_at" | "status" | "uploaded_at"
>;

export async function getTrackPreviewData(
  userId: string,
  trackId: string,
): Promise<TrackPreviewData | null> {
  if (isMockMode) {
    return getMockTrackPreviewData(trackId);
  }

  const supabase = await createClient();
  const { data: membership, error: membershipError } = await supabase
    .from("workspace_members")
    .select("workspace_id")
    .eq("user_id", userId)
    .limit(1)
    .maybeSingle();

  if (membershipError) {
    throw new Error(membershipError.message);
  }

  if (!membership) {
    return null;
  }

  const { data: track, error: trackError } = await supabase
    .from("tracks")
    .select(
      "id, workspace_id, generation_request_id, title, description, tags, style, mood, duration_seconds, audio_storage_path, source_audio_url, image_asset_id, status, failure_reason, created_at",
    )
    .eq("workspace_id", membership.workspace_id)
    .eq("id", trackId)
    .maybeSingle();

  if (trackError) {
    throw new Error(trackError.message);
  }

  if (!track) {
    return null;
  }

  const typedTrack = track as TrackRow;
  const [generation, image, render, upload] = await Promise.all([
    loadGeneration(typedTrack),
    loadImage(typedTrack),
    loadLatestRender(supabase, typedTrack.workspace_id, typedTrack.id),
    loadLatestUpload(supabase, typedTrack.workspace_id, typedTrack.id),
  ]);
  const channel = await loadChannel(
    supabase,
    typedTrack.workspace_id,
    generation?.target_youtube_channel_id ?? null,
  );
  const audioUrl = await resolveAudioUrl({
    path: typedTrack.audio_storage_path,
    sourceUrl: typedTrack.source_audio_url,
    userId,
    workspaceId: typedTrack.workspace_id,
  });
  const coverUrl = await resolveCoverUrl({
    image,
    userId,
    workspaceId: typedTrack.workspace_id,
  });

  return {
    audioUrl,
    channel,
    coverUrl,
    createdAt: typedTrack.created_at,
    description:
      typedTrack.description ??
      "Immerse yourself in a polished instrumental track generated by Bussin. Review the metadata, choose a channel, and approve when the release package is ready.",
    durationSeconds: typedTrack.duration_seconds ?? 165,
    failureReason:
      upload?.failureReason ??
      render?.failureReason ??
      typedTrack.failure_reason,
    generation: generation
      ? {
          finalPrompt: generation.final_prompt,
          id: generation.id,
          mood: generation.mood,
          publishMode: generation.publish_mode,
          scheduledAt: generation.scheduled_at,
          style: generation.style,
        }
      : null,
    imageAssetId: typedTrack.image_asset_id,
    imageMeta: image
      ? {
          fileName: image.file_name,
          height: image.height,
          source: image.source,
          width: image.width,
        }
      : null,
    mood: typedTrack.mood ?? generation?.mood ?? null,
    render,
    status: derivePreviewStatus({ render, track: typedTrack, upload }),
    style: typedTrack.style ?? generation?.style ?? null,
    tags:
      typedTrack.tags && typedTrack.tags.length > 0
        ? typedTrack.tags
        : fallbackTags(typedTrack.style ?? generation?.style),
    title: typedTrack.title ?? "Neon Skyline",
    trackId: typedTrack.id,
    trackStatus: typedTrack.status,
    upload,
    workspaceId: typedTrack.workspace_id,
  };

  async function loadGeneration(track: TrackRow) {
    if (!track.generation_request_id) {
      return null;
    }

    const { data, error } = await supabase
      .from("generation_requests")
      .select(
        "id, style, mood, target_youtube_channel_id, publish_mode, scheduled_at, final_prompt",
      )
      .eq("workspace_id", track.workspace_id)
      .eq("id", track.generation_request_id)
      .maybeSingle();

    if (error) {
      throw new Error(error.message);
    }

    return (data ?? null) as GenerationRow | null;
  }

  async function loadImage(track: TrackRow) {
    if (!track.image_asset_id) {
      return null;
    }

    const { data, error } = await supabase
      .from("image_assets")
      .select("storage_path, public_url, file_name, width, height, source")
      .eq("workspace_id", track.workspace_id)
      .eq("id", track.image_asset_id)
      .maybeSingle();

    if (error) {
      throw new Error(error.message);
    }

    return (data ?? null) as ImageRow | null;
  }
}

async function loadChannel(
  supabase: Awaited<ReturnType<typeof createClient>>,
  workspaceId: string,
  channelId: string | null,
): Promise<TrackPreviewChannel | null> {
  const query = supabase
    .from("youtube_channels")
    .select("id, title, handle, thumbnail_url")
    .eq("workspace_id", workspaceId);
  const { data, error } = channelId
    ? await query.eq("id", channelId).maybeSingle()
    : await query.eq("is_default", true).limit(1).maybeSingle();

  if (error) {
    throw new Error(error.message);
  }

  if (!data) {
    return null;
  }

  const channel = data as ChannelRow;

  return {
    handle: channel.handle,
    id: channel.id,
    thumbnailUrl: channel.thumbnail_url,
    title: channel.title,
  };
}

async function loadLatestRender(
  supabase: Awaited<ReturnType<typeof createClient>>,
  workspaceId: string,
  trackId: string,
): Promise<TrackPreviewRender | null> {
  const { data, error } = await supabase
    .from("video_renders")
    .select("id, track_id, status, video_storage_path, failure_reason")
    .eq("workspace_id", workspaceId)
    .eq("track_id", trackId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }

  const render = data as RenderRow | null;

  return render
    ? {
        failureReason: render.failure_reason,
        id: render.id,
        status: render.status,
        videoStoragePath: render.video_storage_path,
      }
    : null;
}

async function loadLatestUpload(
  supabase: Awaited<ReturnType<typeof createClient>>,
  workspaceId: string,
  trackId: string,
): Promise<TrackPreviewUpload | null> {
  const { data, error } = await supabase
    .from("youtube_uploads")
    .select("id, status, scheduled_at, uploaded_at, failure_reason")
    .eq("workspace_id", workspaceId)
    .eq("track_id", trackId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }

  const upload = data as UploadRow | null;

  return upload
    ? {
        failureReason: upload.failure_reason,
        id: upload.id,
        scheduledAt: upload.scheduled_at,
        status: upload.status,
        uploadedAt: upload.uploaded_at,
      }
    : null;
}

function derivePreviewStatus(input: {
  render: TrackPreviewRender | null;
  track: TrackRow;
  upload: TrackPreviewUpload | null;
}): TrackPreviewStatus {
  if (
    input.upload?.status === "uploaded" ||
    input.track.status === "uploaded"
  ) {
    return "uploaded";
  }

  if (input.upload?.status === "uploading") {
    return "uploading";
  }

  if (
    input.upload?.status === "failed" ||
    input.render?.status === "failed" ||
    input.track.status === "failed"
  ) {
    return "failed";
  }

  if (input.track.status === "rejected") {
    return "rejected";
  }

  if (
    input.render?.status === "rendered" ||
    input.render?.status === "completed"
  ) {
    return "rendered";
  }

  if (input.render && ["queued", "running"].includes(input.render.status)) {
    return "rendering";
  }

  if (input.track.status === "approved") {
    return "approved";
  }

  if (input.track.audio_storage_path || input.track.source_audio_url) {
    return "preview_ready";
  }

  return "audio_loading";
}

async function resolveAudioUrl(input: {
  path: string | null;
  sourceUrl: string | null;
  userId: string;
  workspaceId: string;
}) {
  if (!input.path) {
    return input.sourceUrl;
  }

  return createStorageSignedUrl({
    bucket: "audio-assets",
    path: input.path,
    requesterUserId: input.userId,
    workspaceId: input.workspaceId,
  });
}

async function resolveCoverUrl(input: {
  image: ImageRow | null;
  userId: string;
  workspaceId: string;
}) {
  if (!input.image) {
    return null;
  }

  if (input.image.public_url) {
    return input.image.public_url;
  }

  return createStorageSignedUrl({
    bucket: "image-assets",
    path: input.image.storage_path,
    requesterUserId: input.userId,
    workspaceId: input.workspaceId,
  });
}

function fallbackTags(style: string | null | undefined) {
  const normalizedStyle =
    style?.toLowerCase().replace(/\s+/g, "") ?? "synthwave";

  return [normalizedStyle, "instrumental", "bussin", "newmusic"];
}
