import { env, requireEnv } from "@/lib/env";

const supabasePublicKey = requireEnv(
  env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY",
);

export type PublicEnv = {
  NEXT_PUBLIC_APP_MODE: typeof env.NEXT_PUBLIC_APP_MODE;
  NEXT_PUBLIC_APP_URL: typeof env.NEXT_PUBLIC_APP_URL;
  NEXT_PUBLIC_SUPABASE_PUBLIC_KEY: typeof supabasePublicKey;
  NEXT_PUBLIC_SUPABASE_URL: typeof env.NEXT_PUBLIC_SUPABASE_URL;
};

export const publicEnv: PublicEnv = {
  NEXT_PUBLIC_APP_MODE: env.NEXT_PUBLIC_APP_MODE,
  NEXT_PUBLIC_APP_URL: env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_PUBLIC_KEY: supabasePublicKey,
  NEXT_PUBLIC_SUPABASE_URL: env.NEXT_PUBLIC_SUPABASE_URL,
};
