import type { Metadata } from "next";
import Link from "next/link";
import {
  AudioLines,
  CalendarClock,
  Play,
  Sparkles,
  UploadCloud,
} from "lucide-react";
import { LandingPrompt } from "@/app/landing-prompt";
import { Aurora } from "@/components/common/aurora";
import { Button } from "@/components/ui/button";
import { APP_NAME } from "@/lib/app-public-config";

const examplePrompts = [
  "Chill lofi beats for a late-night study channel",
  "Cinematic instrumental bed for a product launch",
  "High-energy synthwave for workout videos",
];

const workflow = [
  {
    description:
      "Describe the track in one prompt. Suno generates it in minutes.",
    icon: Sparkles,
    title: "Generate",
  },
  {
    description: "Listen to each take and keep only the ones you like.",
    icon: Play,
    title: "Review",
  },
  {
    description:
      "Publish to your YouTube channel now, or schedule it for later.",
    icon: UploadCloud,
    title: "Publish",
  },
];

export const metadata: Metadata = {
  title: `${APP_NAME} - Generate instrumental music for YouTube`,
  description:
    "Type what you want, get instrumental tracks, and publish or schedule them on YouTube — all from one window.",
};

export default function Home() {
  return (
    <main className="flex min-h-[100dvh] flex-col bg-background text-foreground">
      <div className="relative overflow-hidden">
        <header className="sticky top-0 z-40 border-b border-line/60 bg-background/70 backdrop-blur-md">
          <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
            <Link
              className="flex items-center gap-2.5 text-lg tracking-tight"
              href="/"
            >
              <span className="flex size-8 items-center justify-center rounded-lg bg-primary/15 text-primary">
                <AudioLines className="size-5" strokeWidth={2.4} />
              </span>
              <span className="font-display font-semibold">{APP_NAME}</span>
            </Link>
            <nav className="flex items-center gap-2">
              <Button asChild size="sm" variant="ghost">
                <Link href="/login">Sign in</Link>
              </Button>
              <Button asChild size="sm">
                <Link href="/signup">Get started</Link>
              </Button>
            </nav>
          </div>
        </header>

        <section className="relative z-0 mx-auto max-w-3xl px-6 pt-24 pb-20 text-center">
          <Aurora className="-z-10" />
          <div className="inline-flex items-center gap-2 rounded-full border border-line bg-panel/60 px-3 py-1 text-xs text-muted-foreground">
            <Sparkles className="size-3 text-primary" />
            AI music studio for YouTube creators
          </div>
          <h1 className="font-display mt-6 text-5xl leading-[1.05] font-bold tracking-tight sm:text-6xl">
            Type a vibe.
            <span className="block text-primary">Publish a track.</span>
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-lg text-muted-foreground">
            One prompt becomes finished instrumental tracks — generated by Suno,
            rendered to video, and shipped to your YouTube channel on schedule.
          </p>

          <LandingPrompt prompts={examplePrompts} />
        </section>
      </div>

      <section className="mx-auto grid w-full max-w-5xl gap-4 px-6 pb-24 sm:grid-cols-3">
        {workflow.map((item, index) => {
          const Icon = item.icon;

          return (
            <article
              className="group rounded-xl border border-line bg-card/80 p-6 transition-colors hover:border-primary/40"
              key={item.title}
            >
              <div className="flex items-center justify-between">
                <span className="font-mono text-xs text-muted-foreground">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <Icon className="size-4" />
                </span>
              </div>
              <h2 className="font-display mt-4 text-lg font-semibold">
                {item.title}
              </h2>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
                {item.description}
              </p>
            </article>
          );
        })}
      </section>

      <footer className="border-t border-line/60 py-6 text-center text-xs text-muted-foreground">
        <span className="inline-flex items-center gap-1.5">
          <CalendarClock className="size-3.5" />
          Scheduling included — set it and forget it.
        </span>
      </footer>
    </main>
  );
}
