import type { Metadata } from "next";
import Link from "next/link";
import { CalendarClock, Sparkles } from "lucide-react";
import { LandingPrompt } from "@/app/landing-prompt";
import { Aurora } from "@/components/common/aurora";
import { PulseMark } from "@/components/common/logo";
import { Reveal } from "@/components/common/motion";
import { Starfield } from "@/components/common/starfield";
import { Button } from "@/components/ui/button";
import { APP_NAME } from "@/lib/app-public-config";

const examplePrompts = [
  "Chill lofi beats for a late-night study channel",
  "Cinematic instrumental bed for a product launch",
  "High-energy synthwave for workout videos",
];

const workflow = [
  {
    description:
      "Describe the track in one prompt. Suno generates it in minutes.",
    title: "Generate",
  },
  {
    description: "Listen to each take and keep only the ones you like.",
    title: "Review",
  },
  {
    description:
      "Publish to your YouTube channel now, or schedule it for later.",
    title: "Publish",
  },
];

export const metadata: Metadata = {
  title: `${APP_NAME} - Generate instrumental music for YouTube`,
  description:
    "Type what you want, get instrumental tracks, and publish or schedule them on YouTube — all from one window.",
};

export default function Home() {
  return (
    <main className="flex min-h-[100dvh] flex-col bg-background text-foreground">
      <div className="relative isolate overflow-hidden">
        <div
          aria-hidden="true"
          className="grain pointer-events-none absolute inset-0 -z-10"
        >
          <Aurora />
          <Starfield />
        </div>
        <header className="sticky top-0 z-40 border-b border-line/60 bg-background/70 backdrop-blur-md">
          <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
            <Link
              className="flex items-center gap-2.5 text-lg tracking-tight"
              href="/"
            >
              <PulseMark className="size-6" />
              <span className="font-display font-semibold">{APP_NAME}</span>
            </Link>
            <nav className="flex items-center gap-2">
              <Button asChild size="sm" variant="ghost">
                <Link href="/login">Sign in</Link>
              </Button>
              <Button asChild size="sm">
                <Link href="/signup">Get started</Link>
              </Button>
            </nav>
          </div>
        </header>

        <section className="relative z-0 mx-auto max-w-3xl px-6 pt-24 pb-20 text-center">
          <Reveal>
            <div className="inline-flex items-center gap-2 rounded-full border border-line bg-panel/60 px-3 py-1 text-xs text-muted-foreground">
              <Sparkles className="size-3 text-primary" />
              AI music studio for YouTube creators
            </div>
            <h1 className="font-display mt-6 text-5xl leading-[1.05] font-bold tracking-tight sm:text-6xl">
              Type a vibe.
              <span className="block text-primary">Publish a track.</span>
            </h1>
            <p className="mx-auto mt-5 max-w-xl text-lg text-muted-foreground">
              One prompt becomes finished instrumental tracks — generated by
              Suno, rendered to video, and shipped to your YouTube channel on
              schedule.
            </p>
          </Reveal>

          <Reveal delay={0.1}>
            <LandingPrompt prompts={examplePrompts} />
          </Reveal>
        </section>
      </div>

      <section className="mx-auto w-full max-w-5xl px-6 pb-24">
        <div className="grid gap-10 border-t border-line pt-10 sm:grid-cols-3 sm:gap-8">
          {workflow.map((item, index) => (
            <div key={item.title}>
              <span className="font-mono text-xs text-primary">
                {String(index + 1).padStart(2, "0")}
              </span>
              <h2 className="font-display mt-3 text-lg font-semibold">
                {item.title}
              </h2>
              <p className="mt-2 max-w-[36ch] text-sm leading-relaxed text-muted-foreground">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      <footer className="border-t border-line/60 py-6 text-center text-xs text-muted-foreground">
        <span className="inline-flex items-center gap-1.5">
          <CalendarClock className="size-3.5" />
          Scheduling included — set it and forget it.
        </span>
      </footer>
    </main>
  );
}
