// @vitest-environment node

import { describe, expect, it, vi } from "vitest";
import {
  createSunoAdapter,
  validateSunoGenerationInput,
} from "@/server/services/suno/suno-adapter";
import { normalizeSunoError } from "@/server/services/suno/suno.errors";
import {
  createYoutubeUploadAdapter,
  validateYoutubeUploadInput,
} from "@/server/services/youtube/youtube-upload-adapter";
import { normalizeYoutubeError } from "@/server/services/youtube/youtube.errors";
import { maskIntegrationSecret } from "@/server/services/youtube/youtube-oauth.service";

describe("Suno integration adapter", () => {
  it("normalizes provider errors", () => {
    expect(normalizeSunoError({ status: 401 }).code).toBe("unauthorized");
    expect(
      normalizeSunoError({ status: 429, message: "No credits" }).code,
    ).toBe("quota_exceeded");
    expect(normalizeSunoError(new TypeError("fetch failed")).code).toBe(
      "api_unreachable",
    );
    expect(normalizeSunoError({ code: 500, msg: "bad body" }).code).toBe(
      "unknown",
    );
  });

  it("validates generation input before calling Suno", () => {
    expect(() =>
      validateSunoGenerationInput({
        finalPrompt: "",
        makeInstrumental: true,
        style: "lofi",
        title: "",
        waitAudio: false,
      }),
    ).toThrow(/title/i);
  });

  it("sends MVP generation fields and normalizes task id responses", async () => {
    const fetch = vi.fn().mockResolvedValue(
      jsonResponse({
        code: 200,
        data: { taskId: "suno-task-1" },
      }),
    );
    const adapter = createSunoAdapter({
      apiUrl: "https://api.suno.example",
      credential: "test-token",
      fetch,
    });

    await expect(
      adapter.createCustomGeneration({
        finalPrompt: "A focused lo-fi instrumental beat",
        makeInstrumental: true,
        style: "lofi",
        title: "Focus Loop",
        waitAudio: false,
      }),
    ).resolves.toEqual({ sunoTrackId: "suno-task-1" });

    const [, init] = fetch.mock.calls[0];
    expect(JSON.parse(String(init?.body))).toMatchObject({
      customMode: true,
      instrumental: true,
      prompt: "A focused lo-fi instrumental beat",
      style: "lofi",
      title: "Focus Loop",
    });
  });
});

describe("YouTube integration adapter", () => {
  it("normalizes provider errors", () => {
    expect(normalizeYoutubeError({ message: "invalid_grant" }).code).toBe(
      "invalid_grant",
    );
    expect(
      normalizeYoutubeError({
        code: 403,
        errors: [{ reason: "quotaExceeded" }],
      }).code,
    ).toBe("quota_exceeded");
    expect(
      normalizeYoutubeError({
        code: 403,
        errors: [{ reason: "forbidden" }],
      }).code,
    ).toBe("forbidden");
  });

  it("masks tokens without exposing the middle", () => {
    expect(maskIntegrationSecret("ya29.token-value-1234")).toBe("ya29...1234");
    expect(maskIntegrationSecret("short")).toBe("****");
  });

  it("validates upload metadata before calling YouTube", () => {
    expect(() =>
      validateYoutubeUploadInput({
        privacyStatus: "public",
        title: "",
        video: new Uint8Array([1, 2, 3]),
      }),
    ).toThrow(/title/i);
  });

  it("delegates successful uploads to an injected YouTube client", async () => {
    const videosInsert = vi.fn().mockResolvedValue({ data: { id: "yt-123" } });
    const adapter = createYoutubeUploadAdapter({
      createYoutubeClient: () => ({
        videos: { insert: videosInsert, update: vi.fn() },
      }),
    });

    await expect(
      adapter.uploadVideo({
        description: "Generated by Bussin",
        privacyStatus: "unlisted",
        tags: ["lofi", "focus"],
        title: "Focus Loop",
        video: new Uint8Array([1, 2, 3]),
      }),
    ).resolves.toEqual({ youtubeVideoId: "yt-123" });

    expect(videosInsert).toHaveBeenCalledWith(
      expect.objectContaining({
        part: ["snippet", "status"],
        requestBody: expect.objectContaining({
          snippet: expect.objectContaining({ title: "Focus Loop" }),
          status: expect.objectContaining({ privacyStatus: "unlisted" }),
        }),
      }),
    );
  });

  it("normalizes upload adapter failures", async () => {
    const adapter = createYoutubeUploadAdapter({
      createYoutubeClient: () => ({
        videos: {
          insert: vi.fn().mockRejectedValue({
            code: 403,
            errors: [{ reason: "quotaExceeded" }],
          }),
          update: vi.fn(),
        },
      }),
    });

    await expect(
      adapter.uploadVideo({
        privacyStatus: "private",
        title: "Focus Loop",
        video: new Uint8Array([1, 2, 3]),
      }),
    ).rejects.toMatchObject({ code: "quota_exceeded" });
  });
});

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    headers: { "content-type": "application/json" },
    status,
  });
}
